version: '3.8'

services:
  postgres_quiz:
    container_name: postgres_quiz
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pg_quiz